services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/config/passwd:/mosquitto/config/passwd
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  simulator:
    build:
      context: ./simulator
    container_name: simulator
    depends_on:
      - mosquitto
    environment:
      - BROKER_HOST=mosquitto
      - BROKER_PORT=1883
      - DEVICE_ID=device01
      - TOPIC_TELEMETRY=energy/device01/telemetry
      - TOPIC_STATUS=energy/device01/status
      - PUBLISH_INTERVAL_SEC=2
      - HEARTBEAT_INTERVAL_SEC=10
      - ALERT_CURRENT_THRESHOLD=15
      - MQTT_USERNAME=device01
      - MQTT_PASSWORD=energy-2026-secure

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin12345
      - DOCKER_INFLUXDB_INIT_ORG=energy-org
      - DOCKER_INFLUXDB_INIT_BUCKET=energy-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=energy-super-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2

  storage_bridge:
    build:
      context: ./storage_bridge
    container_name: storage_bridge
    depends_on:
      - mosquitto
      - influxdb
    environment:
      - BROKER_HOST=mosquitto
      - BROKER_PORT=1883
      - MQTT_TOPIC=energy/+/telemetry
      - MQTT_USERNAME=device01
      - MQTT_PASSWORD=energy-2026-secure
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=energy-super-token
      - INFLUX_ORG=energy-org
      - INFLUX_BUCKET=energy-bucket
      - INFLUX_MEASUREMENT=energy_telemetry

  nodered:
    build:
      context: ./nodered
    container_name: nodered
    ports:
      - "1880:1880"
    depends_on:
      - mosquitto
    volumes:
      - nodered_data:/data
      - ./dashboard/flows.json:/data/flows.json
      - ./dashboard/flows_cred.json:/data/flows_cred.json

volumes:
  mosquitto_data:
  mosquitto_log:
  influxdb_data:
  influxdb_config:
  nodered_data:
